apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      parallelism: 3
      completions: 3
      template:
        spec:
          containers:
          - name: contos
            image: langhae/msa2:jobsh_v1
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: nginx-log-backup
              mountPath: /var/log/nginx
            command:
            - /test/copy.sh
          restartPolicy: OnFailure
          volumes:
          - name: nginx-log-backup
            persistentVolumeClaim:
              claimName: efs-nginx-log