apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  # namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: nginx-secret
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
          - name: nginx-log
            mountPath: /var/log/nginx
      volumes:
        - name: nginx-conf
          configMap:
            name: web-conf
        - name: nginx-log
          persistentVolumeClaim:
            claimName: efs-nginx-log

