apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mariadb:10.4
        ports:
        - containerPort: 3306
          name: tcp
        envFrom:
          - secretRef:
              name: db-envs
        volumeMounts:
        - name: utf8
          mountPath: /etc/mysql/conf.d
        - name: mariadb-volume
          mountPath: /var/lib/mysql
      volumes:
        - name: utf8
          configMap:
            name: db-utf8
  volumeClaimTemplates:
  - metadata:
      name: mariadb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
